---
title: "Case Study 12"
author: Sandra Notaro
date: November 25, 2020
output: html_document
---

# Preparing the Data
```{r prep, eval=T, echo=T, message=F, cache = T}
library(dplyr)
library(ggplot2)
library(ggmap)
library(htmlwidgets)
library(widgetframe)
library(tidyverse)
library(rnoaa)
library(xts)
library(dygraphs)
```

# Downloading the Daily Weather Data
```{r weather, eval=T, echo=T, message=F, results='hide', cache = T}
d <- meteo_tidy_ghcnd("USW00014733",
                   date_min = "2016-01-01", 
                   var = c("TMAX"),
                   keep_flags=T) %>% 
  mutate(date = as.Date(date), 
         tmax = as.numeric(tmax)/10)
```

# Converting d Into an `xts` Time Series
```{r convert, eval=T, echo=T, message=F, results='hide', cache = T}
d_time_series <- xts(d$tmax, order.by = d$date)
```

# Plot
```{r plot, eval=T, echo=T, message=FALSE, cache=T}
dygraph(d_time_series, main = "Daily Maximum Temperature in Buffalo, NY") %>%
  dyRangeSelector(dateWindow = c("2020-01-01", "2020-10-31")) %>%
  dyOptions(axisLabelFontSize = 12)
# Learned how to change font size with https://cran.r-project.org/web/packages/dygraphs/dygraphs.pdf and https://www.rdocumentation.org/packages/dygraphs/versions/1.1.1.6/topics/dyAxis
```