---
title: "Case Study 09"
author: Sandra Notaro
date: November 1, 2020
output: github_document
---

# Preparing the data

```{r prep, eval=T, echo=F, message=F}
library(sf)
library(tidyverse)
library(ggmap)
library(rnoaa)
library(spData)
data(world)
data(us_states)
library(dplyr)
```

```{r prep2, eval=T, echo=T}
dataurl="https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/shapefile/IBTrACS.NA.list.v04r00.points.zip"
tdir=tempdir()
download.file(dataurl,destfile=file.path(tdir,"temp.zip"))
unzip(file.path(tdir,"temp.zip"),exdir = tdir)
#list.files(tdir)
storm_data <- read_sf(list.files(tdir,pattern=".shp",full.names = T))
```

# Filtering for years 1950s to present and identifying the bounding box of the storm data
```{r filter, echo=T, eval =T}
filtered_1950_present <- storm_data %>%
  filter(SEASON >= 1950) %>%
  mutate_if(is.numeric, function(x) ifelse(x==-999.0,NA,x)) %>%
  mutate(decade=(floor(year/10)*10))
region <- st_bbox(filtered_1950_present)
```

# Plotting maps
``` {r prepplot, echo=F, eval=T, message=F}
storm_plots <- ggplot(world) + geom_sf() + facet_wrap(~decade) +
  stat_bin2d(data = filtered_1950_present, aes(y = st_coordinates(filtered_1950_present)[,2], 
                              x = st_coordinates(filtered_1950_present)[,1]), bins = 100) +
  scale_fill_distiller(palette = "YlOrRd", trans = "log", direction = -1, 
                       breaks = c(1,10,100,1000)) + coord_sf(ylim=region[c(2,4)], 
                                                             xlim=region[c(1,3)]) +
  theme(axis.title.x = element_blank(), axis.title.y = element_blank())
```

```{r plot, echo = F, eval = T}
print(storm_plots)
```

# Reprojecting `us_states` to the reference system of `filtered_1950_present` and renaming `NAME` column to `state`

```{r edits, echo=TRUE, eval =T}
state <- us_states %>%
  st_transform(crs = st_crs(filtered_1950_present)) %>%
  select(state = NAME)
```

# Spatial join between storm database and `state` object
```{r join, echo=T, eval =T, warning=F, message=F}
storm_states <- st_join(filtered_1950_present, state, join = st_intersects,left = F)
```

# Making the table
```{r table prep, echo = F, eval=T, message= F, warning=F}
table <- storm_states %>%
  group_by(state) %>%
  summarize(filtered_1950_present =length(unique(NAME))) %>%
  arrange(desc(filtered_1950_present)) %>%
  slice(1:5) %>%
  st_set_geometry(NULL)
```

``` {r table, echo = F, eval = T}
knitr::kable(table, "simple")
```

Learned how to get rid of geometry column from https://r-spatial.github.io/sf/reference/st_geometry.html
