---
title: "Case Study 11"
author: Sandra Notaro
date: November 16, 2020
output: github_document
editor_options: 
  chunk_output_type: console
---

# Preparing the Data
```{r prep, eval=T, echo=T, message = F, results = 'hide', cache = T}
library(tidyverse)
library(spData)
library(sf)

library(mapview)
library(foreach)
library(doParallel)
registerDoParallel(4)
getDoParWorkers()
library(tidycensus)
library(lwgeom)
library(htmltools)
```

# Getting the tidycensus Data
```{r decennial, eval=T, echo=T, message=F, cache = T}
racevars <- c(White = "P005003", 
              Black = "P005004", 
              Asian = "P005006", 
              Hispanic = "P004003")

options(tigris_use_cache = TRUE)
erie <- get_decennial(geography = "block", variables = racevars, 
                  state = "NY", county = "Erie County", geometry = TRUE,
                  summary_var = "P001001", cache_table=T) 
```

# Creating Max Boundaries
```{r bounds, eval=T, echo=T, message=F, results = 'hide', cache = T}
boundaries <- c(xmin=-78.9,xmax=-78.85,ymin=42.888,ymax=42.92)
cropped <- st_crop(erie, boundaries)
```
Got help from Ting how to crop

# Preparing Dot Plot
```{r filtering, eval=T, echo=T, message=F, cache = T}
groups <- as.factor(cropped$variable)
dotprep <- foreach(i=1:4, .combine = "rbind", .packages = c("tidyverse", "sf")) %dopar% {
  races <- levels(groups)[i]
cropped %>%
    filter(variable == races) %>%
    st_sample(size = .$value) %>%
    st_as_sf() %>%
    mutate(variable = races)
}
```
Ting helped with troubleshooting errors
Used https://www.rdocumentation.org/packages/foreach/versions/1.5.1/topics/foreach for help on how to use `foreach()`

# Map
```{r dotplot, eval=T, echo=T, message=F, as.is=T, cache = T}
dotplot <- mapview(dotprep, zcol = "variable", cex = 1, lwd = 0)
dotplot
```